### ISSUE TITLE
Downloading all segments of a presentation instead of just 1st period.

### ISSUE THREAD

**Issue by niteeshbhat** [Dash-Industry-Forum/DASH-IF-Conformance#110]
conformance software should process the 1st period, but all period's segments are downloaded.
Need to be reviewed.

**Comment by eceozturk** [comment]
This is solved in repository https://github.com/Dash-Industry-Forum/Conformance-Software with commit id 6118bc692e6c6bd088e62c5229b50ff1dab145ca
