### ISSUE TITLE
Error raised for stream with inband parameter sets (ie stsd avc3)

### ISSUE THREAD

**Issue by davemevans** [Dash-Industry-Forum/DASH-IF-Conformance#117]
DASH streams can use the `avc3` sample description to signal parameter sets are carried inband and not in the initialisation segment. This looks to be supported for HEVC, but does not appear to be considered as valid for AVC by the tool. See below for message.

Please add support for avc3 sample description as it is used by a number of content providers.

Example stream: http://rdmedia.bbc.co.uk/dash/ondemand/bbb/2/client_manifest-v1-a2.mpd

```
error: moov-1:trak-1:mdia-1:minf-1:stbl-1:stsd-1
SampleDescription sdType must be 'mp4v', 'avc1', 'encv', 'hev1','hvc1', or 'vp09'('mp4v', 'avc1', 'encv', 'hev1','hvc1','vp09')
```

**Comment by eceozturk** [comment]
avc3 support is added in the repository https://github.com/Dash-Industry-Forum/Conformance-Software in August via repository https://github.com/Dash-Industry-Forum/Conformance-and-reference-source with commit id 6da5619d9adbd12394a02e88016368081a1ca28e. Closing this now.
