### ISSUE TITLE
Incorrect broken URL list reported

### ISSUE THREAD

**Issue by davemevans** [Dash-Industry-Forum/DASH-IF-Conformance#118]
When testing http://rdmedia.bbc.co.uk/dash/ondemand/bbb/2/client_manifest-v1-a2.mpd, the tool reports that there are broken URLs as listed below. These segments should not be accessed - `@startNumber` is not present, so I understand that the value of 1 should be used, giving first segment numbers of 000001.

```
http://rdmedia.bbc.co.uk/dash/ondemand/bbb/2/avc3/512x288p25/000000.m4s
http://rdmedia.bbc.co.uk/dash/ondemand/bbb/2/audio/96kbps/000000.m4s
```

**Comment by eceozturk** [comment]
This issue is fixed in the old repository https://github.com/Dash-Industry-Forum/Conformance-Software. I ran the test and it does not give any broken url list and starts calculating them from 1 as expected. Closing this issue now.
