### ISSUE TITLE
Unknown atom found "avcC" warning raised for H264

### ISSUE THREAD

**Issue by davemevans** [Dash-Industry-Forum/DASH-IF-Conformance#120]
The avcC box contains the MPEG-4 decoder configuration record, and is a required extension to the video sample description for H.264 video, defined in 14496-15.

When finding this, the tool raises an unexpected warning `Warning: Unknown atom found "avcC": video sample descriptions would not normally contain this`

**Comment by eceozturk** [comment]
The conformance tool accepts avcC as a valid atom. Is there any example manifest that raises this warning? And if so, is it possible to share the file for testing?

**Comment by davemevans** [comment]
Back when I filed this, the follwing manifest would trigger this issue: http://rdmedia.bbc.co.uk/dash/ondemand/testcard/1/client_manifest-events.mpd.

Seems it is no longer an issue, closing.
