### ISSUE TITLE
Dynamic Service Conformance should support Segment Templates with format specifier strings in $Number$

### ISSUE THREAD

**Issue by TheJohnBowers** [Dash-Industry-Forum/DASH-IF-Conformance#123]
http://vm1.dashif.org/DynamicServiceValidator/?mpdurl=upload

gives an error validating:

https://content.uplynk.com/channel/3c367669a83b4cdab20cceefac253684.mpd?prettydash=1&ad=cleardashnew

The error is "SegmentTemplate with no $Number$ not supported, exiting!"

My SegmentTemplates all do have $Number$, but only with a format specifier string, so instead of a bare $Number$ they have $Number%08d$

**Comment by eceozturk** [comment]
This issue has been addressed in repository https://github.com/Dash-Industry-Forum/Conformance-and-reference-source with the commit id f7e7d8ba5152ef8062d0c97bcb781eb3ad61db04.

Closing this now
