### ISSUE TITLE
Validator test doesn't complete. Can't find progress.xml (reopen of issue #377)

### ISSUE THREAD

**Issue by pingu0201** [Dash-Industry-Forum/DASH-IF-Conformance#125]
It looks like I'm not allowed to reopen #377, so I'm filing a new issue.   Here's some content that is causing the problems described in #377:

https://cisco.box.com/s/g8x5heovqxbhs0ooznmltd9i644c82ec

Please let me know if that's sufficient or what else I can provide.  Thanks.

**Comment by eceozturk** [comment]
I could not reproduce this issue. When uploaded the provided MPD, the conformance test runs and gets completed without error. If you were using an MPD URL (not file upload), could you provide us with the URL (or any other information that would help us reproduce the issue)?
