### ISSUE TITLE
Check that conformance software can only check https content now.

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/DASH-IF-Conformance#127]
Most probably changed when we moved to https. Check if it is still possible to check http content.

**Comment by eceozturk** [comment]
If user accesses the conformance server from https://conformance.dashif.org, only https URLs are accepted. Failing this condition, a redirect url to http-based page is provided at which http URLs can be tested. If user accesses the conformance server from http://conformance.dashif.org or conformance.dashif.org, http URLs can be tested.
