### ISSUE TITLE
Allow mixed content access

### ISSUE THREAD

**Issue by niteeshbhat** [Dash-Industry-Forum/DASH-IF-Conformance#135]
Allow fetching http based MPD URL from the secure conformance.dashif.org

**Comment by waqarz** [comment]
Is it possible that upon detection that the URL is HTTP (not HTTPs), we **redirect** to the internal HTTP URL? Please check.

**Comment by eceozturk** [comment]
Clarification needed on the expected process and user experience:
- Is it that when the http host is provided in the mpd url, we will open the internal http url in a new tab where the mpd url is either copied to the page url as query string or copied into the input box? In this case how good would it be for the user to see a popup page? Another option would be not new tab but opening on the same tab.
- Is it just the mpd url being carried to the internal page? In this case, the user would have to select the "profile enforcement options" or "MPD conformance only" mode again (if the user selected any in the first place). Or all the options and modes can be carried.
- Any other things to consider regarding this?

**Comment by waqarz** [comment]
Yeah popup etc. are not ideal. What about what we discussed before: a printed report on the page: "HTTP content detected, use this [HTTP-based interface](http://xyz) instead."

**Comment by eceozturk** [comment]
Issue addressed.
PRs: #384 and #385

**Comment by waqarz** [comment]
Change
This secure site will not be processing the content. 
to
This secure (HTTPS) site cannot process the HTTP content.
Make this part Red and bold.

**Comment by eceozturk** [comment]
The requested change is merged. PR #386
