### ISSUE TITLE
MPD validation fails with the following message (xlink resolving stage)

### ISSUE THREAD

**Issue by niteeshbhat** [Dash-Industry-Forum/DASH-IF-Conformance#137]
0sh: 1: http://xxxxxxxxxxxxxxxxxxxxxxxxx/: not found
Needing a file to validate and intermediate file
usage: Validator []
=======================
file to be validated
Name (optionally including path) to store the intermediate xlink resolved file
XSD to be used for validation (optional)

Validation not successful!

**Comment by dsilhavy** [comment]
Closing, unclear description
