### ISSUE TITLE
dashif.org/conformance.html app broken?

### ISSUE THREAD

**Issue by Murmur** [Dash-Industry-Forum/DASH-IF-Conformance#322]
Web application 
http://dashif.org/conformance.html

Is this application broken, it seems to do nothing. Firefox/F12/Console displayes this error over and over.  I tried several mpd url addresses.
```
ML Parsing Error: no root element found
Location: http://54.72.87.160/conformance/current/webfe/temp/id3332375210/progress.xml?1523446902328
Line Number 1, Column 1:
```

**Comment by raskri** [comment]
Should https://dashif.org/conformance.html be up and running?

**Comment by waqarz** [comment]
The URL has moved: http://conformance.dashif.org/
