### ISSUE TITLE
Validator test doesn't complete.  Can't find progress.xml.

### ISSUE THREAD

**Issue by pingu0201** [Dash-Industry-Forum/DASH-IF-Conformance#330]
Using the web-based front-end, my test run doesn't complete.  I see constant messages like this:

conformancetest.php:1166 Failed to load resource: the server responded with a status of 404 (Not Found)

And also these in the HTTP response:

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /conformance/current/webfe/temp/id4691204910/progress.xml was not found on this server.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at conformance.dashif.org Port 443</address>
</body></html>

If I select MPD Conformance-only, it works fine.

I'm new to this tool and could easily be doing something wrong.  Please let me know what info I can provide.  Also, is there any type of user forum or point of contacts for questions, issues, etc?

Thanks.

**Comment by paulserridge** [comment]
I'm seeing same problem on my local build of of master HEAD today.
But same MPD file passed OK on https://conformance.dashif.org/
192.168.123.114 - - [11/Sep/2019:16:52:26 +0000] "GET /DASH-IF-Conformance/Conformance-Frontend/temp/id3892599088/progress.xml?1568220746236 HTTP/1.1" 404 494 "http://rosa.uk.edt.zone/DASH-IF-Conformance/Conformance-Frontend/Conformancetest.php" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"

**Comment by waqarz** [comment]
DASH-IF does not provide support for local installations. Please contact me if you have further questions  .
