### ISSUE TITLE
Manifest requests returning 302 redirects display "Error loading the MPD, please check the URL." 

### ISSUE THREAD

**Issue by ajfayle** [Dash-Industry-Forum/DASH-IF-Conformance#341]
When using https://conformance.dashif.org with a manifest URL that returns a 302 redirect to the actual manifest location the conformance tool is displaying the following error:
- "Error loading the MPD, please check the URL." 

My expectation was that the tool would follow the redirection and validate the manifest returned from the redirected request.

Is it valid according to the DASH specification to expect that a player will follow a 302 redirect to a manifest file or is this a bug with the conformance tool?

**Comment by nicoweilelemental** [comment]
As per section 3.2.15.3 of DASH-IF IOPs, it's totally valid. I have the same validator problem with redirected manifests.

**Comment by dsilhavy** [comment]
Tested with https://livesim.dashif.org/livesim/mup_30/testpic_2s/Manifest.mpd which also returns a 302 and it works. Closing.
