### ISSUE TITLE
Support for new live conformance/dynamic validator features

### ISSUE THREAD

**Issue by eceozturk** [Dash-Industry-Forum/DASH-IF-Conformance#346]
Live conformance/dynamic validator features: 

- UI additions, 
- segment template complete support, 
- UTCTiming support.

**Comment by eceozturk** [comment]
PRs:
- https://github.com/Dash-Industry-Forum/Conformance-and-reference-source/pull/77
- https://github.com/Dash-Industry-Forum/Conformance-and-reference-source/pull/73
- https://github.com/Dash-Industry-Forum/Conformance-and-reference-source/pull/74
- https://github.com/Dash-Industry-Forum/Conformance-and-reference-source/pull/87
- https://github.com/Dash-Industry-Forum/Conformance-and-reference-source/pull/82

UTC timing still needs work.

**Comment by niteeshbhat** [comment]
The UTC timing support is available here 
https://github.com/Dash-Industry-Forum/MPEG-Conformance-and-reference-source/pull/73
It contains support for all schemes already.

The UI additions are open in separate issues in frontend repo here:
https://github.com/Dash-Industry-Forum/Conformance-Frontend/issues
