### ISSUE TITLE
Check for leap seconds-aware UTC timeline (live)

### ISSUE THREAD

**Issue by eceozturk** [Dash-Industry-Forum/DASH-IF-Conformance#360]

**Comment by niteeshbhat** [comment]
From IOP 4.2, it is not clear what is this issue and what is expected from conformance side.
May be more guidelines expected from future specs.

**Comment by niteeshbhat** [comment]
Discussion here : https://github.com/Dash-Industry-Forum/Test-Vectors/issues/103
