### ISSUE TITLE
Stability related issue 

### ISSUE THREAD

**Issue by eceozturk** [Dash-Industry-Forum/DASH-IF-Conformance#361]
- Redirect issue, 
- server loads, 
- file upload issues

**Comment by niteeshbhat** [comment]
At occassions, the server CPU load goes up and warning emails pops up to the admins.
The work on this is ongoing and no concrete conclusions are drawn yet. Some findings are
-Added safety checks for xml file loading (continue processing only when file is opened, pushed adn deployed)..
- the php download ends when the session folder was deleted , this was checked (right now, 2 hours is the deletion time,  tested by making it to 2-5 min in the local system,)
- and another observation, when the session folder is deleted, the frontend will be halted, for that, tried stopping polling in the frontend after 100 failed requests. Not pushed as this is in  frontend and not the actual cause for the CPU load ...

**Comment by waqarz** [comment]
Recent months have not reported any issues, so closing for now.
