### ISSUE TITLE
Outputting a (more) detailed reason of conformance failure

### ISSUE THREAD

**Issue by irajs** [Dash-Industry-Forum/DASH-IF-Conformance#367]
Currently validator doesn't provide any detail information for the reason of conformance failure. For instance it can say if it could not resolve the xlink URL, or which adaptation set/representation attribute or element is missing or wrong.

As a first attempt, the output could be very simple:  for instance providing period number, adaptation set and representation.

**Comment by waqarz** [comment]
@irajs could you provide an example or MPD so we can clarify what is the expected behavior.

**Comment by waqarz** [comment]
I think its more of an enhancement issue, how can:

............mpd:2011'][2]

be easily interpreted as the "second period", and do we have a more user-friendly/understandable print for "IOException", correct @irajs ?

**Comment by irajs** [comment]
I agree. It's not clean, but good enough. It can be improved later.

**Comment by waqarz** [comment]
Lets keep it open till we implement the extensions.
