### ISSUE TITLE
counter log (visitor log) has incomplete lines

### ISSUE THREAD

**Issue by niteeshbhat** [Dash-Industry-Forum/DASH-IF-Conformance#375]
![image](https://user-images.githubusercontent.com/13762418/49817326-33155280-fd70-11e8-9263-1926269b1f59.png)

-There are some incomplete lines ..(may be test is hanged?)
- from above screenshot, line 685 has multiple test logged on single issue.

**Comment by niteeshbhat** [comment]
Regarding the incomplete lines, found the reason that when MPD is uploaded and it is corrupted.
UI frontend shows alert message to check if MPD is correct. However backend stops before updating the visitor log file about the MPD status.
Hence the PR https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/pull/394
will update the visitor log as "uploade- MPD with error". And to see the MPD , the session folder given in the same line of the log file can be opened.

**Comment by niteeshbhat** [comment]
As for issue like line 685,  multiple tests logged on single line is rare and the reason is that the session folder name (random number) is found equal for multiple tests (in the above fig, id5901832025). Hence the result is logged to the first line when the session id is matched. Reason not known yet.

**Comment by niteeshbhat** [comment]
Some additions made to the visitor log in the PR https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/pull/395
#ids are added to each info prints to keep track of missing fields in future logs.
Safety check is added in php to make sure session folder is not repeated.

**Comment by eceozturk** [comment]
Further robustness is done in #460 and #461.
