### ISSUE TITLE
On-demand: Can "MPD conformance only" mode check for indexRange?

### ISSUE THREAD

**Issue by ojw28** [Dash-Industry-Forum/DASH-IF-Conformance#380]
If you do full validation (manifest + media) then there are checks for `indexRange` being present. However no such checks are made in "MPD conformance only" mode. Is it possible to check for `indexRange` in this mode as well? DASH-IOP says:

> For on-demand profiles, the Indexed Media Segment as defined in ISO/IEC 23009-1 11 [4], clause 6.3.4.4 shall be used. In this case the @indexRange attribute shall be present

Which implies to me that checks can be made looking at the manifest only?

**Comment by waqarz** [comment]
@niteeshbhat this check is absent in Schematron: https://github.com/Dash-Industry-Forum/DASH/blob/93154e57de1beaaa720783103a9b7110698e0cc8/mpdvalidator/schematron/schematron.xsd

**Comment by eceozturk** [comment]
Thank you for this observation. The mentioned check is now provided for "MPD conformance only" mode. The PR #382 contains this fix.
