### ISSUE TITLE
Absolute BaseURL at AdaptationSet level, DVB live profile

### ISSUE THREAD

**Issue by Lis-TV** [Dash-Industry-Forum/DASH-IF-Conformance#396]
Accordingly to ETSI TS 103 285 V1.2.1, DVB DASH, 
4.2.4 Constraints on AdaptationSet elements (for Live Periods)

adaptation set/representation with absolute BaseURL may be ignored.
Please add at least warning (error better) in such case. Now MPDs passes validation.

**Comment by waqarz** [comment]
> adaptation set/representation with absolute BaseURL may be ignored.

There is no conformance error or warning to be displayed here. This is a content provisioning issue, that a player **_may_** ignore something.
