### ISSUE TITLE
Target validation of a specific CMAF Media Profile out of many in the manifest

### ISSUE THREAD

**Issue by johnsim** [Dash-Industry-Forum/DASH-IF-Conformance#399]
For both WAVE and CMAF validation (essentially the same), there should be a mechanism for validating a specific media profile contained within the manifest. It should not be necessary to validate all media profiles represented in the manifest.

**Comment by niteeshbhat** [comment]
Solution proposed-
From commandline, user provides a media profile to validate. For example, to validate avc_hd profile, 

-d 'profile= "avc_hd"'

After conformance test, the output would contain the following results showing which tracks conforms to the provided profile.

Information: Switching set 1 Track 1 is conforming to the given media profile- 'avc_hd'
Information: Switching set 1 Track 2 is conforming to the given media profile- 'avc_hd'
etc..

If in the case of no tracks found conforming to the given profile, then we print,
Information: No tracks found conforming to the given media profile 'avchd'.

The above method is extended to provide multiple profiles, for example,
-d 'profile= ["avc_hd","hhd10","uhd10"]'

**Comment by johnsim** [comment]
good solution. may be preferable to identify the profiles by their defined 4CC - 'cfhd', 'chh1', 'cud1' - and/or by their WAVE defined Media Profile Name - HD, HHD10, UHD10

**Comment by niteeshbhat** [comment]
The above solution has been implemented. The media profile names or the 4CC can be used.
The related PR is 
https://github.com/Dash-Industry-Forum/CMAF/pull/7

The usage document has been updated too. Can be found here
https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/blob/master/Doc/Usage_Guide_for_Conformance_Software.pdf
