### ISSUE TITLE
Multiperiod stops working (for second and higher periods) in the following two scenarios

### ISSUE THREAD

**Issue by niteeshbhat** [Dash-Industry-Forum/DASH-IF-Conformance#417]
when there is a xlink period, ex:
http://10.4.247.98/server/dash264/TestCases/5b/nomor/10.mpd

other case is http://10.4.247.98/server/dash264/TestCases/5b/nomor/2.mpd

**Comment by niteeshbhat** [comment]
the second case mentioned above is fixed here
https://github.com/Dash-Industry-Forum/Conformance-Frontend/pull/61

**Comment by dsilhavy** [comment]
Tested and works with:

* https://dash.akamaized.net/dash264/TestCases/5b/nomor/10.mpd
* https://dash.akamaized.net/dash264/TestCases/5b/nomor/2.mpd
