### ISSUE TITLE
Fatal error with PHP 7.1

### ISSUE THREAD

**Issue by andyburras** [Dash-Industry-Forum/DASH-IF-Conformance#434]
In MPDProcessing.php:

> check_before_segment_validation();
> ...
> function check_before_segment_validation($result_for_json){
> 

This results in:

> Fatal error: Uncaught ArgumentCountError: Too few arguments to function check_before_segment_validation(), 0 passed in /var/www/html/DASH-IF-Conformance/DASH/MPDProcessing.php on line 164 and exactly 1 expected in /var/www/html/DASH-IF-Conformance/DASH/MPDProcessing.php on line <i>279</i>

 
Prior to PHP 7.1 this would just generate a warning, but in PHP 7.1 this has been promoted to a Fatal error. So validation fails with the latest PHP.

**Comment by eceozturk** [comment]
This issue was fixed in https://github.com/Dash-Industry-Forum/DASH/pull/22. Closing this issue now.
