### ISSUE TITLE
Fixing php errors

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/DASH-IF-Conformance#442]
We have strange prints in the code like:
error_log("downloaddata_Missing:" . $filePath);

This is wrong on so many levels:

- If there is an error, what use is it to print it in a file where no one checks it?
- Such error should be handled properly:
> - Do the software need to do something to handle this error? If not,
> -do the user need to be informed of this error? 
- Finally, printing this in the log file lets it grow without bounds. This is bad programming!

**Comment by eceozturk** [comment]
Huge prints of the same error_log() is removed in PR #456. 
Each download error is actually provided to user on the UI as broken url on the results tree.

Now the log file does not grow in size; however, some other php logs can still be removed or shortened.
