### ISSUE TITLE
Install: Java 1.8 is no more available

### ISSUE THREAD

**Issue by ngaullier** [Dash-Industry-Forum/DASH-IF-Conformance#444]
As commented here:
https://tecadmin.net/install-oracle-java-8-ubuntu-via-ppa/
License terms have changed recently and it is not possible to install java8, even manually.

**Comment by dsilhavy** [comment]
Java 8 installation works, see: https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/wiki/Installation--guide

````
sudo apt-get install openjdk-8-jdk
update-alternatives --list java
sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java 
sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
````
