### ISSUE TITLE
Trying to run live content just does not work

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/DASH-IF-Conformance#447]
- Does not show the option to run dynamic conformance for e.g. a dynamic MPD: https://vm2.dashif.org/livesim-dev/periods_1/testpic_2s/Manifest.mpd
- Was stuck last time I used

**Comment by waqarz** [comment]
Some updates:
The URL is throwing errors to the[ cache bypass technique](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#Bypassing_the_cache) used, e.g. URL: http://vm2.dashif.org/livesim-dev/periods_1/testpic_2s/Manifest.mpd?1560849939915
Response:
Unknown file extension: .mpd?1560849939915

Also the new live sim URL does the same: http://livesim.dashif.org/livesim-dev/periods_1/testpic_2s/Manifest.mpd?1560849939915

So its taking the benign query string as a part of the URL.

**Comment by waqarz** [comment]
Relates to: https://github.com/Dash-Industry-Forum/dash-live-source-simulator/issues/80

**Comment by dsilhavy** [comment]
Closing, livesim urls work
