### ISSUE TITLE
DASH Validator v4.1a Broken

### ISSUE THREAD

**Issue by FullstackJack** [Dash-Industry-Forum/DASH-IF-Conformance#448]
The official DASH validator found at https://conformance.dashif.org/ does not work.

When you try to validate an MPD, the page says Processing..., but the console shows hundreds of 404s with the following message:

`The requested URL /conformance/current/Conformance-Frontend/temp/id4516047790/progress.xml was not found on this server.`

There is also a 500 internal server error on `https://conformance.dashif.org/conformance/current/Utils/Process.php`

**Comment by iamprem** [comment]
Any update on this? I've been noticing this for the past few days and still not working as mentioned by the OP.

**Comment by waqarz** [comment]
@eceozturk the server must be full again, we need to fix this: https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/issues/442

**Comment by eceozturk** [comment]
Thank you @FullstackJack and @iamprem for reporting this issue. This has been the result of the issue reported in #442. Right now, I have provided a temporary fix; so, the conformance tool runs fine. The permanent fix will be provided soon.

Closing this issue right now. Please feel free to reopen if the same problem occurs until the permanent fix is done.
