### ISSUE TITLE
Filtering for submodules for repo sync not working

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/DASH-IF-Conformance#450]
The script https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/blob/master/tools/RepoSync/sync.sh so far has not been successful in not pushing the unneeded submodules; therefore, the script itself is not in its final version.

**Comment by eceozturk** [comment]
Update on this is provided in the commit 1bf058e5f0f7591a199749468b5884a279d87116.
Now, the syncing works. 
One manual thing required right now is to visit the desired main repository (that the changes are being pushed) and merge the newly created branch "sync" to branch "master". This should also be checked if it is possible to do it via the script.

**Comment by waqarz** [comment]
I think its fine to do the final merge manually. Please add this info in bold in the readme
