### ISSUE TITLE
Only MPD is processed, but not the segments

### ISSUE THREAD

**Issue by satninfy** [Dash-Industry-Forum/DASH-IF-Conformance#457]
![CMAF_MPD](https://user-images.githubusercontent.com/36437868/62193656-104ea300-b32d-11e9-9844-8215d15e3fa0.JPG)
When I choose "Choose a File or Drag it here" option and select an MPD from a local drive in my PC and start the Test, I see that MPD validation succeeds, but segments are not processed at all even though I have not checked "MPD Conformance only" option.
I'm not sure what the issue is. I have verified that the segments are available at the corresponding locations. MPD is pasted here for reference. Screen-shot of the Test execution is also attached.

**_<?xml version="1.0" ?>
<MPD mediaPresentationDuration="PT1M52.212S" minBufferTime="PT3.00S" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011" type="static" xmlns="urn:mpeg:dash:schema:mpd:2011">
  
  <Period>
    
    <AdaptationSet maxHeight="480" maxWidth="854" mimeType="video/mp4" segmentAlignment="true" startWithSAP="1">
      <SegmentTemplate initialization="$RepresentationID$/init.mp4" media="$RepresentationID$/seg-$Number$.m4s" startNumber="1" timescale="30000">
        <SegmentTimeline>
          <S d="90090" r="36"/>
          <S d="33033"/>
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation bandwidth="2191075" codecs="avc1.42C01F" frameRate="30000/1001" height="480" id="video/avc1/1" scanType="progressive" width="854"/>
      <Representation bandwidth="4912900" codecs="avc1.42C01F" frameRate="30000/1001" height="480" id="video/avc1/2" scanType="progressive" width="854"/>
      <Representation bandwidth="947044" codecs="avc1.42C01F" frameRate="30000/1001" height="480" id="video/avc1/3" scanType="progressive" width="854"/>
    </AdaptationSet>
  </Period>
</MPD>_**

![CMAF4](https://user-images.githubusercontent.com/36437868/62193501-bbab2800-b32c-11e9-8073-ff506d06f3eb.JPG)

Any help is appreciated.

**Comment by waqarz** [comment]
In this case, you need to have a BaseURL on the MPD level that points to the segment location. Please reopen if this does not help

**Comment by satninfy** [comment]
@waqarz 
Thanks for the quick turnaround. 

I have my MPD here:
D:\ATT\CMAF\output\1564069489\

Segments are in the following folders (for the 3 Bit-rates):
D:\ATT\CMAF\output\1564069489\video\avc1\1\
D:\ATT\CMAF\output\1564069489\video\avc1\2\
D:\ATT\CMAF\output\1564069489\video\avc1\3\

I'm not very clear on your statement "you need to have a BaseURL on the MPD level that points to the segment location". 
**Should I have it as <BaseURL>D:\ATT\CMAF\output\1564069489\</BaseURL> ?**
 I tried it and it is not working.

[ Note that media="$RepresentationID$/seg-$Number$.m4s resolves the remaining part of URL (\video\avc1\1\ for eg.,) ]
 
Thanks in advance



Note that

**Comment by waqarz** [comment]
@satninfy the segments _must_ be on an HTTP server _accessible_ by the conformance software, the software cannot access segments from your local file server.

**Comment by satninfy** [comment]
@waqarz 
 I was using the Conformance Software from Public URL https://conformance.dashif.org and uploading the MPD from my local PC. Since Conformance Software at this location can't access Segments from my Local PC and I have no way of hosting the segments on a Public HTTP server accessible by the Conformance Software, It looks like I have to setup the Conformance Software in a local Ubuntu machine and host the content (MPD and segments) in a local HTTP Server. 

Thanks for the support.
