### ISSUE TITLE
Move all DASH-IF schematron checks together

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/DASH-IF-Conformance#46]
Move all DASH-IF schematron checks together towards the end of the file so that its easier to address them separately.

**Comment by waqarz** [comment]
R1.7 is not making any sense at all. Understood, this rule is common to DASH ecosystem so it should stay where it is. The print however is not making any sense. Change it from

The live profile shall be identified by the URN urn:mpeg:.........

to

An unknown profile string (other than urn:mpeg:....... /*all known profile strings here*/) found.

If we can put the name of this unknown profile string in the print, its better.

**Comment by niteeshbhat** [comment]
Fixed.
https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/pull/381
