### ISSUE TITLE
UI footer has issue

### ISSUE THREAD

**Issue by niteeshbhat** [Dash-Industry-Forum/DASH-IF-Conformance#48]
<a href="https://github.com/niteeshbhat"><img src="https://avatars3.githubusercontent.com/u/13762418?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [niteeshbhat](https://github.com/niteeshbhat)**
_Thursday Sep 20, 2018 at 11:42 GMT_
_Originally opened as https://github.com/Dash-Industry-Forum/Conformance-Software/issues/406_

----

![image](https://user-images.githubusercontent.com/13762418/45816098-f3901a80-bcda-11e8-9a56-787cb787799b.png)

**Comment by niteeshbhat** [comment]
<a href="https://github.com/niteeshbhat"><img src="https://avatars3.githubusercontent.com/u/13762418?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [niteeshbhat](https://github.com/niteeshbhat)**
_Thursday Sep 20, 2018 at 11:42 GMT_

----

If footer cant be brought down, then it may be better to remove color of the footer.

**Comment by niteeshbhat** [comment]
<a href="https://github.com/niteeshbhat"><img src="https://avatars3.githubusercontent.com/u/13762418?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [niteeshbhat](https://github.com/niteeshbhat)**
_Thursday Sep 20, 2018 at 11:44 GMT_

----

Assigning @lisiensemanjaku

**Comment by eceozturk** [comment]
This issue is addressed in https://github.com/Dash-Industry-Forum/Conformance-Frontend with commit id 87e78e14e54fbe4c1a29db14906ba2ba60c1c367

Closing this now.
