### ISSUE TITLE
Unclear error on text tracks of MPEG's CMAF conformance stream

### ISSUE THREAD

**Issue by boy-vd** [Dash-Industry-Forum/DASH-IF-Conformance#480]
This issue is related to #479, as it's about the same stream and similarly unclear errors, the difference being that these are reported on different tracks. The stream in question is the MPEG conformance stream for CMAF: https://usp-cmaf-test.s3.eu-central-1.amazonaws.com/tears-of-steel.mpd.

In addition to the unclear error on the video tracks (#479), there is are two errors on the WebVTT text tracks that are equally unclear.

**My question is whether this is the validator misreporting an error because it cannot parse something that it should be able to parse, or whether there is actually something wrong with track?**

For the text tracks, the two errors that are unclear are shown below. The errors are the same for all the text tracks:
```
(2 repetition\s) ### error: moov-1:trak-1:mdia-1:minf-1:stbl-1:stsd-1 
### Validate_ES_Descriptor: Not enough bits left in the bitstream for further attribute validation
### Validate_mp4s_ES_Bitstream: Not enough bits left in the bitstream for further attribute validation
```

However, when I use [MP4Box.js](https://gpac.github.io/mp4box.js/test/filereader.html) it seems to be able to read the `stsd` box just fine (see below). Also, playback of the stream in DASH.js 3.0 doesn't produce any problems.

Information from one of the video tracks (https://usp-cmaf-test.s3.eu-central-1.amazonaws.com/tears-of-steel-nl.cmft) taken from `MP4Box.js`:

`moov` > `trak` > `mdia` > `minf` > `stbl` > `stsd`
```
type                 stsd
size                 46
flags                0
version              0
start                433
```
`stsd` > `wvtt`
```
type                 wvtt
size                 30
start                449
data_reference_index 1
data                 0000000e 76747443 57454256 5454
```
`stsd` > `vttC`
```
type                 vttC
size                 14
start                465
data                 57454256 5454
text                 WEBVTT
```

If you need more info, please let me know :-)!

**Comment by boy-vd** [comment]
The validator produces some informational messages for all text tracks as well, which may or may not be of value for the understanding of the unclear errors reported above:
```
SampleDescription sdType must be 'mp4s'
'ESDAtom' flags must be 0 not 0x454256
ESDAtom version must be 0 not 0x57
Validate_ES_Descriptor: Tag != Class_ES_DescrTag
```

**Comment by rbouqueau** [comment]
I confirm the error is gone.
