### ISSUE TITLE
Duration errors for live CMAF content

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/DASH-IF-Conformance#481]
Can CMAF duration tests be run on live CMAF content? Or are these for static content only?

**'CMAF check violated: Section 7.3.6 - 'The duration of a CMAF presentation shall be the duration of its longest CMAF track', but not found (Presentation time= 0 and longest Track= 24)
**'CMAF check violated: Section 7.3.6-'CMAF Tracks in a CMAF Presentation SHALL equal the CMAF Presentation duration within a tolerance of the longest video CMAF Fragment duration ', but not found in the Track 0
**'CMAF check violated: Section 7.3.6-'CMAF Tracks in a CMAF Presentation SHALL equal the CMAF Presentation duration within a tolerance of the longest video CMAF Fragment duration ', but not found in the Track 1

**Comment by eceozturk** [comment]
After reading through DASH specification (ISO/IEC 23009-1) clauses 5.3.1.2, 5.3.2.1 and A3.2, it seems that in case the MPD@mediaPresentationDuration and last Period@duration are not present, the presentation duration is unknown. 

In such a case, conformance software computes the presentation duration as 0 and hence the error log. 

This is now changed as the following (commit 934066145b87ef4acefec95d335f3667f46583e3):
- Presentation duration related checks (Section 7.3.6) are skipped if the presentation duration is found out to be unknown.
- Presentation duration related checks (Section 7.3.6) are performed if the presentation duration is successfully computed.

Closing this issue now.
