### ISSUE TITLE
Unexpected error: String index out of range: -5 cryptic messages

### ISSUE THREAD

**Issue by nicoweilelemental** [Dash-Industry-Forum/DASH-IF-Conformance#484]
Hi,

I'm getting cryptic error messages like:

Unexpected error: String index out of range: -5 
java.lang.StringIndexOutOfBoundsException: String index out of range: -5 
at java.lang.String.substring(String.java:1967) 
at XLinkResolver.parseXML(XLinkResolver.java:217) 
at XLinkResolver.resolveXLinks(XLinkResolver.java:73) 
at Validator.main(Unknown Source) 
Validation not successful! 

Example URLs: 
https://d24rwxnt7vw9qb.cloudfront.net/v1/dash/e6d234965645b411ad572802b6c9d5a10799c9c1/All_Reference_Streams/4577dca5f8a44756875ab5cc913cd1f1/index.mpd?aws.sessionId=57f6ec78-2f9f-486d-a48d-657b1f25336a 
  
https://d24rwxnt7vw9qb.cloudfront.net/v1/dash/e6d234965645b411ad572802b6c9d5a10799c9c1/All_Reference_Streams/91d37b0389de47e0b5266736d3633077/index.mpd?aws.sessionId=eedbce2e-3bd6-4406-84cb-e6b9994dfce9 
  
https://d24rwxnt7vw9qb.cloudfront.net/v1/dash/e6d234965645b411ad572802b6c9d5a10799c9c1/All_Reference_Streams/ee565ea510cb4b4d8df5f48918c3d6dc/index.mpd?aws.sessionId=1f592689-8fac-4b14-a33a-ddb4c89669e8 

Thanks for your help,
Nicolas

**Comment by eceozturk** [comment]
This was a bug related to a string operation. It is fixed in the commit a0245f9

**Comment by linehammer** [comment]
A StringIndexOutOfBoundsException is thrown when a String or StringBuffer object detects an out-of-range index. An out-of-range index occurs when the index is less than zero, or greater than or equal to the length of the string.  Using the [substring](http://net-informations.com/java/string/substring.htm) method, a subset of the character sequence can be extracted from a string. The substring index must be any value from 0 to the length of a string. If the index exceeds the limit, StringIndexOutOfBoundsException is thrown in String substring method.

**How to solve the StringIndexOutOfBoundsException**

-     Check the length of the string.
-     Exception handling using try...catch.
