### ISSUE TITLE
invalid SegmentTemplate error for static profile

### ISSUE THREAD

**Issue by mihaiav** [Dash-Industry-Forum/DASH-IF-Conformance#485]
I'm trying to validate a manifest file with the online validator ( https://conformance.dashif.org/ ) . The error I get is:  `For live profile, the SegmentTemplate element shall be present on at least one of the three levels, the Period level containing the Representation, the Adaptation Set containing the Representation, or on Representation level itself.`
  Why do I get this error? The profile of the manifest is static not "live".  

https://liveradio.s3.eu-central-1.amazonaws.com/manifest.mpd

**Comment by eceozturk** [comment]
This is a constraint provided in ISO/IEC 23009-1 section 8.4.2. The manifest type is static; however the profile is live profile which mandates the use of SegmentTemplate. 

Closing this now, please feel free to reopen if any further questions
