### ISSUE TITLE
Cross check and fix schematron

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/DASH-IF-Conformance#488]
A.4.2
The schema contains a cross-reference to a specific element of a document, but this has not been dated (as per Directives Part 2). Can the code be changed by inserting a date?

(descendant::dash:Representation/@frameRate &lt; @minFrameRate)) or 
(@maxFrameRate and (descendant::dash:Representation/@frameRate > 
@maxFrameRate))) then false() else true()">ISO/IEC 23009-1 Section 
5.3.3.2: The value of the frameRate attribute shall be in the range 
defined by the AdaptationSet.</assert>
            
              </rule>
       </pattern>

Should be: ISO/IEC 23009-1: 2019, 5.3.3.2

A.4.2, A.4.3, A.4.4.31, A.4.4.49 and A.4.4.50
The text in A.4.3 contains references to ISO/IEC 23001-8 in the descriptions for FramePacking and AudioChannelConfiguration and the schemas in the other subclauses contain requirements to use it too, but ISO/IEC 23001-8 has been cancelled and replaced by ISO/IEC 23091 (all parts) and all cross-references to ISO/IEC 23001-8 should be updated accordingly. ISO/IEC 23091 (all parts) will also need to be listed in Clause 2 due to this normative citation within the schemas. Can each of these cross-references in the text and code be changed or is it necessary to retain the references to a withdrawn standard?:

                        
                        <assert test="if (not(@value = '0' or @value = '1' or @value = '2' or @value = '3' or @value = '4' or @value = '5' or @value = '6')) then false() else true()">The value of FramePacking shall be 0 to 6 as defined in ISO/IEC 23001-8.</assert>
                 </rule>
                                                                </pattern>

Should be: shall be 0 to 6 as defined in ISO/IEC 23091(all parts)

**Comment by edrthomas** [comment]
it would be great if this can be fixed by the end of the week (January 17th) as ISO expects the revised document from me by January 22. Thanks !

**Comment by edrthomas** [comment]
@waqarz @eceozturk as discussed, it would be great if this can be fixed today. Then I can repackage the conformance software and send it along with the text to ISO. Look forward to hearing from you.

**Comment by eceozturk** [comment]
@edrthomas I have assigned myself to this issue and the fix will be provided today. I will update the status from here

**Comment by eceozturk** [comment]
Updates are done via 5c5c33c38100a68205729b2abae83c5f25f81686. This commit is also deployed on the conformance tool server (https://conformance.dashif.org/).

**Comment by edrthomas** [comment]
@eceozturk thanks for the fix. However the first one is not completely exact. It seems ISO suggest removing the world "Section" in from the of the section number. Could you please fix this too? Thanks !

**Comment by eceozturk** [comment]
@edrthomas thank you for noticing this. I updated the code (including the changes in the ISOSegmentValidator according to the new specification notation with ",") via 4170a599866277ac6c7adb6ad7627e8725ceb690 and deployed it on the server. 

If all seems fine, this issue can be closed.
