### ISSUE TITLE
Stuck On Processing

### ISSUE THREAD

**Issue by tsumpter921** [Dash-Industry-Forum/DASH-IF-Conformance#490]
Yesterday was working fine. Today nothing loads, including the same manifests that were working yesterday. Stuck on "Processing..."

![image](https://user-images.githubusercontent.com/40596602/73069927-508f7800-3eaf-11ea-8eae-bc559d451d5a.png)

**Comment by salva84** [comment]
Same issue for me

**Comment by eceozturk** [comment]
Right now, it seems like the server is down. Currently working on it and will update here once it is up and running.

**Comment by eceozturk** [comment]
Up and running now. If confirmed, this issue can be closed.

**Comment by salva84** [comment]
failing again...

**Comment by eceozturk** [comment]
I have restarted the server yesterday. So it is up and running. 
Unfortunately, there is not. But I opened up a stability issue (https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/issues/492) to keep track of this and fix it permanently rather than just restarting.

**Comment by mokojo200** [comment]
Hi this is still an issue stuck on processing
