### ISSUE TITLE
Web tool Dash Validator is not working.

### ISSUE THREAD

**Issue by mgregor** [Dash-Industry-Forum/DASH-IF-Conformance#491]
Just keeps making this call:

over and over and over... :-)

Conformancetest.php:726 GET https://conformance.dashif.org/conformance/current/Conformance-Frontend/temp/id9139023597/progress.xml?1580332461388 404 (Not Found)
progressupdate @ Conformancetest.php:726
(anonymous) @ Conformancetest.php:830

Conformancetest.php:1565 GET https://conformance.dashif.org/conformance/current/Conformance-Frontend/temp/id9139023597/progress.xml 404 (Not Found)
loadXMLDoc @ Conformancetest.php:1565
pollingProgress @ Conformancetest.php:836
(anonymous) @ Conformancetest.php:831

Conformancetest.php:726 GET https://conformance.dashif.org/conformance/current/Conformance-Frontend/temp/id9139023597/progress.xml?1580332462486 404 (Not Found)
progressupdate @ Conformancetest.php:726
(anonymous) @ Conformancetest.php:830
Conformancetest.php:1565 GET

**Comment by eceozturk** [comment]
It is fixed now. Closing this issue. Please feel free to reopen if any further problems.

**Comment by zhulduz** [comment]
It is not working again (
