### ISSUE TITLE
Does not return result 

### ISSUE THREAD

**Issue by Radresingen** [Dash-Industry-Forum/DASH-IF-Conformance#494]
I am trying to validate a mpd manifest. However, both with file and url options i see front-end related error(i guess) and the site does not return a result. 

Conformancetest.php:1565 GET https://conformance.dashif.org/conformance/current/Conformance-Frontend/temp/id9294944865/progress.xml 404 (Not Found) the error i get.

**Comment by LienLotus** [comment]
I have the same issue, so many 404 errors and the validator can not be completed, still "Processing". Anyone knows how can we fix?
![Screenshot from 2020-02-25 09-56-59](https://user-images.githubusercontent.com/51039899/75211028-5a114600-57b5-11ea-990d-7efec0c602c1.png)

**Comment by eceozturk** [comment]
Up and running right now. 
But there is a stability issue (#492) open to keep track of this and fix it more permanently.
