### ISSUE TITLE
ContentProtection not allowed inside Representation?

### ISSUE THREAD

**Issue by Romain-Bernier** [Dash-Industry-Forum/DASH-IF-Conformance#495]
Mpd validator message : 

Line:Col[39:46]:cvc-complex-type.2.4.d: Invalid content was found starting with element 'ContentProtection'. No child element is expected at this point.

Line:Col[67:46]:cvc-complex-type.2.4.d: Invalid content was found starting with element 'ContentProtection'. No child element is expected at this point.

Line:Col[95:46]:cvc-complex-type.2.4.d: Invalid content was found starting with element 'ContentProtection'. No child element is expected at this point.

Line:Col[123:46]:cvc-complex-type.2.4.d: Invalid content was found starting with element 'ContentProtection'. No child element is expected at this point.

Line:Col[158:43]:cvc-complex-type.2.4.a: Invalid content was found starting with element 'ContentProtection'. One of '{"urn:mpeg:dash:schema:mpd:2011":Representation}' is expected.

Line:Col[191:43]:cvc-complex-type.2.4.a: Invalid content was found starting with element 'ContentProtection'. One of '{"urn:mpeg:dash:schema:mpd:2011":Representation}' is expected.

Line:Col[224:43]:cvc-complex-type.2.4.a: Invalid content was found starting with element 'ContentProtection'. One of '{"urn:mpeg:dash:schema:mpd:2011":Representation}' is expected.

MPD validation not successful - DASH is not valid!

But the ISO/IEC 23009-1:2019(E) version of the Dash (part1 Table13) says that it's ok to have the ContentProtection element inside the Representation element.

**Comment by eceozturk** [comment]
The schema used in the validator accepts ContentProtection element within Representation element (see below image).

![image](https://user-images.githubusercontent.com/35132231/75968327-7c9a1200-5ecd-11ea-8b23-8433e441b300.png)

My guess (without seeing the tested MPD) is that the error is because of the order of the elements within the Representation. The elements in the MPD should follow the order as they appear in the schema. For example for an audio Representation if you have ContentProtection before the AudioChannelConfiguration, then you would get an error in the MPD Validation step. 

If this is not the case, sharing the tested MPD would be helpful for troubleshooting.

**Comment by Romain-Bernier** [comment]
Thanks for your reply 

<Representation >
           <SegmentTemplate>
                    <SegmentTimeline>
                              <S>
                    </SegmentTimeline>
          </SegmentTemplate>
          <ContentProtection/>
          <ContentProtection>
                    <cenc:pssh>/cenc:pssh>
          </ContentProtection>
</Representation>

I have the following order of element inside my mpd, this order is not right ?

**Comment by eceozturk** [comment]
The below is the schema for the Representation. According to this RepresentationBaseType should appear before BaseURL, SegmentTemplate, etc.

![image](https://user-images.githubusercontent.com/35132231/75981111-17055000-5ee4-11ea-956d-84a8b93c6704.png)

If the MPD is modifiable by you, you can directly cut and paste the SegmentTemplate after RepresentationBaseType elements.

**Comment by Romain-Bernier** [comment]
Ok, thanks for your reply

**Comment by Romain-Bernier** [comment]
Thank for your help eceozturk, can you explain to me why the following manifest is not correct (I have change the mpd to put contentprotection before segment template) ?

[mpd_example.txt](https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/files/4293864/mpd_example.txt)
