### ISSUE TITLE
EventStream/Event cannot have characters because type is element-only

### ISSUE THREAD

**Issue by Murmur** [Dash-Industry-Forum/DASH-IF-Conformance#497]
[Validator](https://conformance.dashif.org/) gives an error `Line:Col[13:89]:cvc-complex-type.2.3: Element 'Event' cannot have character [children], because the type's content type is element-only`  but I think this is a mistake. Event element may have a message data which is mapped to `HTML5 CueData.data` field just like is done for `EMSG.message_data` payload field. See HbbTV_2.0.1_specification/9.3.2.2 HTML5 media element DataCue property.

https://refapp.hbbtv.org/videos/00_llama_multiperiod_v1/manifest.mpd

```
<EventStream schemeIdUri="http://hbbtv.org/refapp" value="1a2b3m" timescale="1000">
   <Event presentationTime="0"     duration="2000" id="10">MPD event(start,0s)</Event>
   <Event presentationTime="1000"  duration="2000" id="11">MPD event(playing,1s)</Event>
   <Event presentationTime="60000" duration="2000" id="12">MPD event(end,60s)</Event>
</EventStream>
```

**Comment by Murmur** [comment]
Hm...well...is this changed in a later specs? Schema file has `Event@messageData` attribute for a payload value.
https://github.com/Dash-Industry-Forum/DASH/blob/master/mpdvalidator/schemas/DASH-MPD.xsd
```
  <xs:complexType name="EventType">
    <xs:sequence>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
      <xs:attribute name="presentationTime" type="xs:unsignedLong" default="0"/>
      <xs:attribute name="duration" type="xs:unsignedLong"/>
      <xs:attribute name="id" type="xs:unsignedInt"/>
      <xs:attribute name="messageData" type="xs:string"/>
    <xs:anyAttribute namespace="##other" processContents="lax"/>
  </xs:complexType>
```

Several dash pdf files has examples like this.
```
**ts_103285v010301p.pdf**
<EventStream schemeIdUri="urn:dvb:iptv:cpm:2014" value="1">
 <Event presentationTime="300" duration="1500" id="0">something</Event>
 </EventStream> 

**HbbTV-SPEC20-00023-002-HbbTV_2.0.1_specification_for_publication_clean.pdf**
The string value of the <Event>element.

**Dash_c065274_ISO_IEC_23009-1_2014.pdf**
<EventStream schemeIdUri="urn:uuid:XYZY" timescale="1000" value="call">
 <Event presentationTime="0" duration="10000" id="0">+ 1 800 10101010</Event>
 <Event presentationTime="20000" duration="10000" id="1">+ 1 800 10101011</Event>
 </EventStream>
```

**Comment by eceozturk** [comment]
Yes this seems to have changed in the DASH specification 4th edition (ISO/IEC 23009-1). We are going to update the conformance software according to the 4th edition changes. 
Until it happens, the conformance software actually supports user-selected schema validation. For this it uses query string "schema".

One example to use the 4th edition schema would be:
http://54.72.87.160/conformance/current/Conformance-Frontend/Conformancetest.php?schema=https://raw.githubusercontent.com/MPEGGroup/DASHSchema/4th-AMD1/DASH-MPD.xsd

In this way the error should disappear.

**Comment by Murmur** [comment]
Thanks for the verification I modified a test manifest and validator is more happy now, next step is an extensive playback test on various devices.
https://refapp.hbbtv.org/videos/00_llama_multiperiod_v1/manifest_asid.mpd

**Comment by eceozturk** [comment]
Glad to help! Closing this issue now
