### ISSUE TITLE
Web tool Dash Validator is not working

### ISSUE THREAD

**Issue by zhulduz** [Dash-Industry-Forum/DASH-IF-Conformance#499]
Hi everyone, can you please fix the issue? There is no opportunity to check Dash playlists.
<img width="1676" alt="Screenshot 2020-04-01 at 15 56 46" src="https://user-images.githubusercontent.com/1921276/78112845-654d3680-7431-11ea-9902-1f8b2c5f7cab.png">

**Comment by eceozturk** [comment]
It should be working now
