### ISSUE TITLE
Stuck on processing

### ISSUE THREAD

**Issue by mohanaprakash** [Dash-Industry-Forum/DASH-IF-Conformance#500]
After selecting and pressing GO icon, no response.
It got stuck in processing.

**Comment by LienLotus** [comment]
I have the same issue, how can we bypass ?

**Comment by eceozturk** [comment]
It could have been some storage issue, I could not reproduce. So, the issue might have gone. Could you try running a test again?

**Comment by CharlieBonilla** [comment]
Same problem for me... No response from website.
![Captura](https://user-images.githubusercontent.com/60752504/79595938-04d02180-80e0-11ea-8737-ad7683d858f4.JPG)

**Comment by ffiore1** [comment]
Same for me

Summary
URL: https://conformance.dashif.org/conformance/current/Conformance-Frontend/temp/id1019219801/progress.xml?1587333674327
Status: 404 Not Found
Source: Network
Address: 54.72.87.160:443
Initiator: 
Conformancetest.php:776

**Comment by eceozturk** [comment]
I did some cleanup on the server, I think it should work now.

**Comment by LienLotus** [comment]
We have this issue back now, @eceozturk  could you please check. Thanks!

**Comment by eceozturk** [comment]
Should be fixed already.
