### ISSUE TITLE
progress.xml?1590999240517 throws Status Code: 404 Not Found while validation 

### ISSUE THREAD

**Issue by mateors** [Dash-Industry-Forum/DASH-IF-Conformance#506]
i am getting a 404 page error from progress.xml?1590999240517 page
while validating my mpd manifest https://master-erp.com/dash/02/clearkey_manifest.mpd
and getting **Error loading the MPD, please check the URL.**

please have a look at the below screen

![image](https://user-images.githubusercontent.com/17635146/83389618-50c9f200-a412-11ea-9c60-c5e247d82c20.png)

but when i am uploading the file then no error and seems everything alright, check below screen shot.

![image](https://user-images.githubusercontent.com/17635146/83390113-1c0a6a80-a413-11ea-9b69-1b6f88bf0293.png)

any suggestion whats wrong? how can i get rid of this error?

**Comment by eceozturk** [comment]
Should be fixed already.
