### ISSUE TITLE
http-based interface does not work

### ISSUE THREAD

**Issue by LienLotus** [Dash-Industry-Forum/DASH-IF-Conformance#509]
Use this HTTP interface to check, but it is unaccessible:
![Screenshot from 2020-06-16 10-05-50](https://user-images.githubusercontent.com/51039899/84727299-eb046b00-afb8-11ea-9995-36170fa10bfa.png)

http://54.72.87.160/conformance/current/Conformance-Frontend/Conformancetest.php
![Screenshot from 2020-06-16 10-05-03](https://user-images.githubusercontent.com/51039899/84727226-ce683300-afb8-11ea-9a5f-d39f48b29211.png)

**Comment by eceozturk** [comment]
We have recently changed the user interface and this issue is an oversight. This bug will be fixed, thanks for reporting!

**Comment by LienLotus** [comment]
@eceozturk 
Is this working now?
I can use: http://conformance.dashif.org/conformance/current/Conformance-Frontend/index.html
Do you know which link I can see all my report ?
Thanks!

**Comment by rbouqueau** [comment]
Works for me. Closing.
