### ISSUE TITLE
Can not validate by using "enter URL"

### ISSUE THREAD

**Issue by LienLotus** [Dash-Industry-Forum/DASH-IF-Conformance#510]
Validate DASH Output by enter URL:
https://https-proxy01.anevia.com/172.27.119.174/live/setelia_disk/elemental/dash_time/elemental.mpd

Face this issue:
![Screenshot from 2020-06-16 10-47-52](https://user-images.githubusercontent.com/51039899/84729790-c612f680-afbe-11ea-8830-1cefc2dc776a.png)

## Remark: No issue when uploading a file and validate

![Screenshot from 2020-06-16 10-49-32](https://user-images.githubusercontent.com/51039899/84729896-02deed80-afbf-11ea-89fc-2179517febee.png)

**Comment by eceozturk** [comment]
The provided URL seems to be not accessible. I checked it on Google Chrome browser and the result is:
![image](https://user-images.githubusercontent.com/35132231/84739642-467c2c00-afac-11ea-8208-f88cef1018ca.png)

**Comment by LienLotus** [comment]
Hi @eceozturk 
The dash manifest I mentioned is the tested URL from my side (you can not access).
You can check with your local URL (https protocol)

**Comment by dsilhavy** [comment]
Url input works in general, closing
