### ISSUE TITLE
404's

### ISSUE THREAD

**Issue by interpegasus** [Dash-Industry-Forum/DASH-IF-Conformance#511]
Hi, Some of the scripts at https://conformance.dashif.org/ return 404's

Could you please check?  Thank you

<img width="1077" alt="Screen Shot 2020-06-22 at 3 20 34 PM" src="https://user-images.githubusercontent.com/934795/85331619-177a2480-b49c-11ea-93e1-5375a6d43221.png">

**File Validation**

<img width="1092" alt="Screen Shot 2020-06-22 at 3 23 19 PM" src="https://user-images.githubusercontent.com/934795/85331763-57410c00-b49c-11ea-91f5-a3312dcbcfb5.png">

**Comment by koln67** [comment]
I'm getting a 404 error when opening some logs relating to adaptation sets. 

Not Found
The requested URL was not found on this server.

Apache/2.4.18 (Ubuntu) Server at conformance.dashif.org Port 443




The browser console shows the following error:
stepperController.js:497 GET https://conformance.dashif.org/conformance/current/DASH-IF-Conformance/Conformance-Frontend/temp/id4451271048/Period0/Adapt1rep0log.html 404 (Not Found)

**Comment by interpegasus** [comment]
The validation seems to be working fine now on my end.

<img width="1006" alt="Screen Shot 2020-06-23 at 3 19 19 PM" src="https://user-images.githubusercontent.com/934795/85456817-fa5d5880-b564-11ea-8f46-f01a03dcefc7.png">
 
But the JS console still displays some errors. Perhaps there is work in progress or it is a reliability issue.

**Comment by koln67** [comment]
Yeah, it mostly works for me as well, except that one of the error logs for the file I used doesn't seem to open. It might be a local issue for me though.

**Comment by interpegasus** [comment]
Hi, I have re-tested with a new manifest:

`https://dash.akamaized.net/envivio/EnvivioDash3/manifest.mpd
`

And the web-tool is not working again. Perhaps it is a reliability issue or the site is being updated. I am using latest Chrome Mac OS.
Please let me know in case you need more information for debugging. Thanks.

**Comment by mansch** [comment]
Same here, tool is not working and it looks like the server run out of space - the Progress.php returns several errors all beloning together:
<b>Warning</b>:  Unknown: write failed: No space left on device (28) in <b>Unknown</b> on line <b>0</b><br />

**Comment by RodolpheFouquet** [comment]
Hi, trhis should have been fixed, can you confirm?

**Comment by mansch** [comment]
It's actually working. Will this be an temporary effect again? :)

**Comment by RodolpheFouquet** [comment]
It was a disk space issue, I've fixed the server adding more space, and I'm working on something to alert me when the server is about to be full so I can take preventive actions.

This won't happen again.
