### ISSUE TITLE
conformance.dashif.org stopped working - server out of space

### ISSUE THREAD

**Issue by mansch** [Dash-Industry-Forum/DASH-IF-Conformance#515]
The server run out of space, no online validation possible.
Progress.php shows a lot of errors and finally
Warning: Unknown: write failed: No space left on device (28) in Unknown on line 0

**Comment by eceozturk** [comment]
Seems to be working, could you please check again?

**Comment by mansch** [comment]
Working. But .. you'd fixed something? tried it 3 days w/o success :)

**Comment by cbisaillon** [comment]
Not working again

**Comment by mansch** [comment]
Yes, same error again - Warning: Unknown: write failed: No space left on device (28) in Unknown on line 0

Any chance to change the behavior to a longer lasting one? E.g. cleaning up temp folder regulary?

**Comment by louaybassbouss** [comment]
I also checked it today still not working and receive the following error (tested in Chrome Browser on Mac)
![image](https://user-images.githubusercontent.com/1138409/86589762-8c665780-bf8e-11ea-9a51-0d3d83c7b4b4.png)

**Comment by thomshutt** [comment]
This has been broken every time I've checked for a week or so now

**Comment by LienLotus** [comment]
We have this issue now.
It stop working with both "Upload URL" or "Enter URL" .
No progress is displayed, stuck in running.
@eceozturk  can you check ?
Thanks!

**Comment by 89z** [comment]
https://github.com/zencoder/go-dash/issues/81
