### ISSUE TITLE
 DASH-IF-Conformance  is not working, stuck in running

### ISSUE THREAD

**Issue by LienLotus** [Dash-Industry-Forum/DASH-IF-Conformance#516]
Dash-if Conformance Tool  is not working since few days.
Steps:

- Open https://conformance.dashif.org/
- Select "START"
- Enter this URL: https://livesim.dashif.org/livesim/chunkdur_1/ato_7/testpic4_8s/Manifest300.mpd
- Select "RUN"

No progress is displayed, no results displayed, stuck in running
![Screenshot from 2020-07-09 22-05-42](https://user-images.githubusercontent.com/51039899/87057221-ca82a600-c230-11ea-9b01-3abe849ef6f9.png)

**Comment by RodolpheFouquet** [comment]
Hi, the server was out of disk space.

It has been fixed now, can you confoirm it?

**Comment by LienLotus** [comment]
Hi,
It's working today.
This issue happened many times, we should prevent it in the future.
Thanks!

**Comment by RodolpheFouquet** [comment]
I've increased the disk size by a lot, and I'll add some alarm to check when the disk gets full.
