### ISSUE TITLE
ISOSegmentValidator issues

### ISSUE THREAD

**Issue by koln67** [Dash-Industry-Forum/DASH-IF-Conformance#517]
Hi, could someone look at some of the issues in the ISOSegmentValidator submodule? Thanks!

https://github.com/Dash-Industry-Forum/ISOSegmentValidator/issues

**Comment by RodolpheFouquet** [comment]
Hi, the whole conformance project in the process of a handover.

I'm now in charge of the project, I'll have a look.

**Comment by dsilhavy** [comment]
Issues in ISOSegmentValidator are checked separately
