### ISSUE TITLE
DASH-IF-Conformance server requirements

### ISSUE THREAD

**Issue by chanof** [Dash-Industry-Forum/DASH-IF-Conformance#519]
Hello, I tried to validate my mpd (www.unknow.tv/live/manifest.mpd), in the past in order to validate it i know about to activate CORS, now I can't find the requirements, I read about that the conformance web tool on https://conformance.dashif.org need that my web server is on https.
Before implementing something wrong I want ask about which are the requirements for server to accomplish the validation:
Do I need CORS? Do I need https certificate web server?
Thank a lot!
Gian

**Comment by dsilhavy** [comment]
* You can call the conformance software from http://conformance.dashif.org/ then you dont need https
* CORS need to be enabled on your server or add the origin conformance.dashif.org to the list of allowed origins
