### ISSUE TITLE
http-based interface is not working

### ISSUE THREAD

**Issue by LienLotus** [Dash-Industry-Forum/DASH-IF-Conformance#520]
In the last time, I can do some tests with http://conformance.dashif.org/conformance/current/DASH-IF-Conformance/Conformance-Frontend/index.html
But it's not working for now.
![Screenshot from 2020-08-05 18-22-08](https://user-images.githubusercontent.com/51039899/89407184-85c32f80-d748-11ea-919a-d47c9e1154cb.png)

Can you tell me which URL is correct for http interface  AND which URL I can see all my reports ?

**Comment by dsilhavy** [comment]
URL is this one: http://conformance.dashif.org/
