### ISSUE TITLE
Help needed in running HLS validation

### ISSUE THREAD

**Issue by lotusnm** [Dash-Industry-Forum/DASH-IF-Conformance#533]
On running command-line execution like:
curl -d 'url="https://media.axprod.net/TestVectors/v9-MultiFormat/Clear/Manifest_1080p.m3u8"' -d cmaf http://localhost/DASH-IF-Conformance/Utils/Process.php

I am getting below warning for all of the Adapt and rep. 
Warning: simplexml_load_file(): /var/www/html/DASH-IF-Conformance/Conformance-Frontend/temp/id1892597027/Period0/Adapt0/Adapt0rep8.xml:1: parser error : Document is empty in /var/www/html/DASH-IF-Conformance/Utils/Load.php

I am sure I am not running the validation for HLS properly. Can you please guide me on how to validate one of the test HLS manifest?

**Comment by rbouqueau** [comment]
Closing because too old. Please comment if needed.
