### ISSUE TITLE
A general CMAF Ingest Question

### ISSUE THREAD

**Issue by ggnull35** [Dash-Industry-Forum/DASH-IF-Conformance#534]
Hi,

I checked the spec documents and I couldnt be sure for HTTP Pull CMAF compliance.
Can Ingest source (encoder) put the chunks on storage and can CDN HTTP Pull these chunks ? 
Is this a valid approach.

Kind Regards,

**Comment by dsilhavy** [comment]
You need a manifest (DASH or HLS) to use with the conformance tool
