### ISSUE TITLE
$Number$ attribute calculate

### ISSUE THREAD

**Issue by junmediatek** [Dash-Industry-Forum/DASH-IF-Conformance#535]
Hi 
When we study mpeg dash spec, we meet a problem as below:
Mpeg dash fourth spec as below
If the Representation contains or inherits a SegmentTemplate element with $Number$ then the URL of the Media Segment at position k in the Representation is determined by replacing the $Number$ identifier by (k−1) + (kstart−1) with kstart the value of the @startNumber attribute, if present, or 1 otherwise.

Mpeg dash second spec as below
If the Representation contains or inherits a SegmentTemplate element with $Number$ then the URL of the Media Segment at position k in the Representation is determined by replacing the $Number$ identifier by (k-1) + @startNumber.

So, which one is right for $Number$?

**Comment by dsilhavy** [comment]
From 5th edition:

If the Representation contains or inherits a SegmentTemplate element with $Number$ then the URL of the Media Segment i, MediaSegment.URL[i], is obtained by replacing the $Number$ identifier by i−1 + @startNumber in the SegmentTemplate@media string
