### ISSUE TITLE
Submodules link not updated to the latest commit

### ISSUE THREAD

**Issue by yanj-github** [Dash-Industry-Forum/DASH-IF-Conformance#540]
Submodules linked are not the latest commit.
e.g: ISOSegmentValidator linked commit is 677843b990
      But the latest ISOSegmentValidator is 764a0558fc

**Comment by rbouqueau** [comment]
see https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/commits/master

I've added the existing deploy script. Unfortunately it takes all the tip commit of master branch to make the update. Something we'll need to address while refactoring the codebase.
