### ISSUE TITLE
Support for IOP 4.3 clauses 3.10.2 and 4.6

### ISSUE THREAD

**Issue by tafinho** [Dash-Industry-Forum/DASH-IF-Conformance#543]
On the current validator, the following validation error is obtained if a @type = static and period@start is non zero:

- If MPD is of type "static" and the first period has a start attribute the start attribute shall be zero.

This directly contradicts the following IOP 4.3 clauses:

3.10.2

where @type must be static and period@start must be present and relative to MPD's AST.

4.6.2

The MPD@availabilityStartTime should be removed or be maintained from the live MPD since all resources referenced in the MPD are available. If the MPD@availabilityStartTime is maintained for a portion of the live program that is offered in the static MPD the Period@start value (including the presentation time offset and the start number) and the presentation duration shall be set accordingly. **The relationship to the wall-clock time should be maintained by offsetting the Period@start without changing the MPD@availabilityStartTime**.

**Comment by RufaelDev** [comment]
yes this is also common in case of live multi-period content converted to a static for example were ealier presentation would be missing. This case of live to  static conversion is what introduces this, i think the main restriction would be the profile, in the on demand profile @start would be 0, but in case of static mpd with live profile this may not be the case, such as when it resulted from a live to static conversion

**Comment by Phencys** [comment]
Closing as this is now solved
