### ISSUE TITLE
404s

### ISSUE THREAD

**Issue by dbanbahji** [Dash-Industry-Forum/DASH-IF-Conformance#544]
I see the same issue as this one with 404 on the progress route looping, is the server out of disk space?
https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/issues/511

**Comment by rbouqueau** [comment]
Thanks for reporting. Could you retry please?

The server seemed to have been restored in a previous state that was inconsistent. I've uploaded the executables and purged the Temp folder (/var/www/html/conformance/current/Conformance-Frontend/temp/).

**Comment by kockodo** [comment]
Hi @rbouqueau I have the same problem.  yesterday and today the same situation
![chrome_2021-12-16_23-27-06](https://user-images.githubusercontent.com/96268004/146458497-12941220-b917-467c-8bf8-b754fa34b21a.png)

**Comment by kockodo** [comment]
@rbouqueau I have the same situation. Could you fix this please.
![chrome_2021-12-16_23-27-06](https://user-images.githubusercontent.com/96268004/146507809-3a437383-7784-41ab-b900-9507943ca4ef.png)

**Comment by rbouqueau** [comment]
This time the disk is full. I'll have a look.

**Comment by rbouqueau** [comment]
I've freed some space. But looking at the log I've noticed that some checks seem to loop forever, slowing eating resources in the background.

**Comment by rbouqueau** [comment]
It seems more stable now but leaving this open until I understand better what's happening.

**Comment by kockodo** [comment]
Yes it works now. Thanks for fast help :)

**Comment by kockodo** [comment]
@rbouqueau I regret to inform you but it doesn't work again :( again 404 errors

**Comment by rbouqueau** [comment]
The disk was full again :(

I've freed the space. I'll have a look to the core issue next week.

**Comment by dbanbahji** [comment]
Its 404ing again.

**Comment by rbouqueau** [comment]
Thanks. Disk full again (temporarily fixed).

I had put traces this time, I'll analyze what happened.

**Comment by rbouqueau** [comment]
I could isolate the issue on the server. Then I had to debug step by step to isolate a few places in the code that looked incorrect.

I keep the tab of this issue open but please don't hesitate to report again if you see this error.
