### ISSUE TITLE
Segment Validation problem on audio validation

### ISSUE THREAD

**Issue by yanj-github** [Dash-Industry-Forum/DASH-IF-Conformance#545]
When validating audio streams (aac that I have checked with), the Segment Validation Report gives "error### Failed to process Adaptation Set 0, Representation 0!"
Further investigating shows that the function run_backend from SegmentValidation.php returned failure. 
Return code is 139 segmentation fault after executing ValidateMP4.exe from function run_backend.
It seems like ValidateMP4.exe (ISOSegmentValidator module) is causing segmentation fault.

**Comment by rbouqueau** [comment]
Thanks for reporting. Are you able to share an audio file sample for investigation?

**Comment by yanj-github** [comment]
The test stream that I used was still under development. 
Same error reported to audio representation for https://dash.akamaized.net/WAVE/vectors/2021-09-09/avc_sets/15_30_60/t1/. You can use this for investigation.

**Comment by rbouqueau** [comment]
I don't see the issue anymore. Closing.
