### ISSUE TITLE
Segment validation results are not the same as in conformance server

### ISSUE THREAD

**Issue by kpopcz** [Dash-Industry-Forum/DASH-IF-Conformance#546]
Hi,

using [https://conformance.dashif.org/](https://conformance.dashif.org/) with segment validation results with error: 
```
  ### error: ### ../src/ValidateAtomList.cpp : 1148 : ### error: ### No 'ftyp' atoms
  ### error: ### ../src/ValidateAtomList.cpp : 1148 : ### error: ### No 'moov' atoms
```
After setting up my own conformance tool (Ubuntu 18.04 64-bit) I got the same error as :[https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/issues/545]( https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/issues/545 ). After deep investigation, it looks like the published compiled _ValidateMP4.exe_ was compiled on newer Linux because there is a lack of GLPC 28 and 29. My next step was to recompile _ValidateMP4.exe_ on my machine. After recompiling, I got good-looking segment validation logs (atoms error vanished). 

**But, if I compile ValidateMP4 for 64-bit (delete _-m32_ option from a makefile) I started getting the same atoms error as mentioned previously.** Debbuger session confirms that on compiled 64-bit _ValidateMP4.exe_ reads wrong sizes, and skips first atoms what causes the problem. 
My question is it possible that _ValidateMP4.exe_ present on the conformance tool server is corrupted - bad compilation, etc.? Is it ok that after recompiling _ValidateMP4.exe_  I got different segment validation logs? 

Thanks,
Kamil

**Comment by rbouqueau** [comment]
Hi,

Thanks for your message with detailed information. We'll have a look soon.

The ValidateMP4.exe status is broken. Depending on the compiler and platform it will crash randomly. So I had to remove the "-m32" and now we get this error.

FYI a new [project](https://dashif.org/news/jscsp/) wrt the conformance checker was emitted. There should be massive improvements on stability this year.

**Comment by rbouqueau** [comment]
Seems like this was fixed. Please reopen if you still see the issue.
