### ISSUE TITLE
Progress bar not taking CMAF processing into account

### ISSUE THREAD

**Issue by cconcolato** [Dash-Industry-Forum/DASH-IF-Conformance#551]
When I request Segment Validation and CMAF validation, the progress bar is full after the Segment Validation, then nothing happens for a moment (but the button still shows "STOP" and not "GO BACK"), and finally the CMAF results appear. This is quite confusing.

**Comment by rbouqueau** [comment]
There is no progress bar anymore. CMAF seems to be processed like any other profile. Closing.
