### ISSUE TITLE
CMAF-only validation not working

### ISSUE THREAD

**Issue by cconcolato** [Dash-Industry-Forum/DASH-IF-Conformance#553]
When I try the conformance tool from https://conformance.dashif.org/, if I set only the CMAF validation (no HbbTV or DVB or CTA ...), it never happens. I have to set "Segment Validation" to get the CMAF validation, but then I get DASH-specific errors which are not CMAF errors (e.g. "error- DASH ISO/IEC 23009-1, 7.2.1: 'The maximum tolerance of segment duration shall be +/-50% of the signaled segment duration (@duration)'"). An example of MPD to test is [this one](https://download.tsi.telecom-paristech.fr/gpac/DASH_CONFORMANCE/TelecomParisTech/mp4-live/mp4-live-mpd-A-NBS.mpd).

**Comment by rbouqueau** [comment]
Works now. Closing.
