### ISSUE TITLE
Profile information in UI only works when segment validation is done

### ISSUE THREAD

**Issue by eceozturk** [Dash-Industry-Forum/DASH-IF-Conformance#555]
Profile information is reported in the UI to provide information on the validation scope. However this only works when segment validation is done. This should be provided also for MPD validation-only cases.

![profiles](https://user-images.githubusercontent.com/35132231/72785476-a0f6a380-3c2b-11ea-87ef-4efef6bd86ec.png)
Figure 1: Profile information provided

![profiles1](https://user-images.githubusercontent.com/35132231/72785507-ace26580-3c2b-11ea-853b-d52c74eaa25c.png)
Figure 2: Profile information not provided when MPD conformance only

**Comment by rbouqueau** [comment]
New front has been deployed.
