### ISSUE TITLE
UI changes for BW/MBT tool

### ISSUE THREAD

**Issue by niteeshbhat** [Dash-Industry-Forum/DASH-IF-Conformance#556]
1.	These interface items should scale according to page and tend to be in the *middle* of the page.

 
2.	By default, the values in the boxes cannot be edited, just like now.
3.	Add 2 more buttons (total 3 buttons in a row, in the following order):
a.	Manually edit values
i.	Behavior:
1.	Enabled by default, 
2.	Once clicked
a.	it enables editing of the values in both the boxes, and
b.	greyed out once clicked.
b.	Reset to MPD values
i.	Once clicked, both boxes take the initial values from the MPD.
c.	The final button “Estimate” is already here, behavior needs updating:
i.	Once estimate calculation is done:
1.	The estimate button should get disabled, until someone clicks Manually one of the first two buttons (edit values button or Reset to MPD values).
2.	The estimated value in the box should change color once the estimation is done, e.g. the background color of this text box should change to green to show user its done.
a.	This color should be rest to white once the user clicks one of the first two buttons.

**Comment by rbouqueau** [comment]
This was closed when the UI was updated.
