### ISSUE TITLE
Backend issue: sequence number is not mandated to increase anymore in ISO BMFF

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/DASH-IF-Conformance#56]

**Comment by niteeshbhat** [comment]
This issue is repeated here https://github.com/Dash-Industry-Forum/ISOSegmentValidator/issues/14
 and already fixed. 
The related PRs
https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/pull/426
https://github.com/Dash-Industry-Forum/ISOSegmentValidator/pull/17
