### ISSUE TITLE
On-Demand Services with Live profiles and first Period element validation failed

### ISSUE THREAD

**Issue by ssadovski007** [Dash-Industry-Forum/DASH-IF-Conformance#561]
Schematron validation is not successful for the manifest composed as "On-Demand Services with Live profiles" if the first `<Period/>` element has `start` attribute not `0`.

Manifest header sample:

`
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" profiles="urn:mpeg:dash:profile:isoff-live:2011" type="static" availabilityStartTime="1970-01-01T00:00:00Z" mediaPresentationDuration="PT30M0S" maxSegmentDuration="PT2.006S" minBufferTime="PT0S">
    <Period id="0" start="PT432100H35M1.514S">
`

Validator produces the following error:

`location="/*[local-name()='MPD' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011']">`
If MPD is of type "static" and the first period has a start attribute the start attribute shall be zero.

As per DASH-IF spec https://dashif.org/docs/DASH-IF-IOP-v4.3.pdf
3.10.2. On-Demand Services with Live profiles
25 3.10.2.1. MPD Information
`MPD@type` optional, if present set to `"static"`

It seems, `profiles="urn:mpeg:dash:profile:isoff-live:2011"`attribute is ignored during validation  and the validator considers the manifest as On-Demand (VoD).

**Comment by andyburras** [comment]
Thanks @wschidol - I've raised it as a different issue: https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/issues/595
