### ISSUE TITLE
BitRateBox in sample entry

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/DASH-IF-Conformance#571]
https://dvb-2017-dm.s3.eu-central-1.amazonaws.com/philips.mpd

message :unknown atom found "btrt": video sample descriptions would not normally contain this this seems incorrect:

From mpeg-4 part 15: 

8.4.1.1.1	Definition
Sample Entry and Box Types:	'hvc1', 'hev1', 'hvcC'
Container:	Sample Table Box ('stbl')
Mandatory:	An 'hvc1' or 'hev1' sample entry is mandatory
Quantity:	One or more sample entries may be present
An HEVC visual sample entry shall contain an HEVC Configuration Box, as defined below. This includes an HEVCDecoderConfigurationRecord, as defined in ‎8.3.3.1.
An optional BitRateBox may be present in the HEVC visual sample entry to signal the bit rate information of the HEVC video stream. Extension descriptors that should be inserted into the Elementary Stream Descriptor, when used in MPEG-4, may also be present.
4.3.4	Optional boxes in the sample entry
Unless otherwise explicitly specified, the optional boxes, including the BitRateBox, in the sample entry document the information for the output bitstream by the file parser reconstructed from this track and all the tracks this track depends on for decoding.

**Comment by rbouqueau** [comment]
I don't see the initial issue anymore. The 'color' issue is in #671.
