### ISSUE TITLE
Segment Validation of CENC encrypted content crashes if CMAF option is selected

### ISSUE THREAD

**Issue by andyburras** [Dash-Industry-Forum/DASH-IF-Conformance#587]
The Segment Validation of CENC encypted content reports "free(): invalid pointer" but **only** if the CMAF option is selected. Without the CMAF selected it runs through fine.

**Comment by rbouqueau** [comment]
Works with https://dash.akamaized.net/WAVE/vectors/cfhd_sets/12.5_25_50/t1-cenc/2023-09-01/stream.mpd. Closing.
