### ISSUE TITLE
404 progress.xml - Test stays stuck

### ISSUE THREAD

**Issue by Coralielm** [Dash-Industry-Forum/DASH-IF-Conformance#588]
Hi,

I'm trying to test this manifest: https://dash.akamaized.net/akamai/bbb_30fps/bbb_30fps.mpd
On https://conformance.dashif.org/

But unfortunatly the test never ends and progress bar doesn't move.
I've got a lot of 404 concerning progress.xml file

![image](https://user-images.githubusercontent.com/7912766/175335523-c60a80ba-1d49-4e8e-b2fc-759f1172cce9.png)

Could you please tell me if there is any workaround here?
Thank you!

**Comment by dsilhavy** [comment]
@Coralielm Thank you for pointing this out. Can you please try again, the machine ran into a memory problem. This should be fixed now.

**Comment by Coralielm** [comment]
Hi @dsilhavy,

Thank you for your quick reply and fix.
It's working perfectlty now.

Best,
C
