### ISSUE TITLE
Incorrect request for first segment '.m4s' instead of '0.m4s'

### ISSUE THREAD

**Issue by nicholas-fr** [Dash-Industry-Forum/DASH-IF-Conformance#604]
When testing CTA WAVE test vectors the first segment (after init segment) is not requested correctly.

For example with:
`php Process_cli.php --cmaf --ctawave --segments http://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t1/2022-10-17/stream.mpd`

There seems to be an issue with the 0 value as '.m4s' is requested instead of '0.m4s':

![image](https://user-images.githubusercontent.com/9865551/199961225-165b9613-d298-4113-82ba-e2682bfa2fac.png)

**Comment by nicholas-fr** [comment]
This issue is still seen in the latest development release (commit https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/commit/626fe38b47b1988b07249e8673e0f82d8cb571ce).
Also worth noting that following the 404 response sent by some servers (e.g. using the basic Python http.server) the conformance tool gets stuck in an infinite loop, constantly re-sending the same incorrect request:

![image](https://user-images.githubusercontent.com/9865551/200808466-8e4938ae-370d-4da7-baa9-5a6bc25166f6.png)

**Comment by dsilhavy** [comment]
We merged #611 can you please check if this fixes your problem

**Comment by nicholas-fr** [comment]
Confirmed fixed using the latest dev branch (https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/commit/310009a13957add8525e2043bc617936dffc71ee).

![image](https://user-images.githubusercontent.com/9865551/201052185-a8e45fd5-66aa-46c2-af1e-ad72096553ab.png)
