### ISSUE TITLE
temp directory not created on a clean install

### ISSUE THREAD

**Issue by andyburras** [Dash-Industry-Forum/DASH-IF-Conformance#615]
Installed v2.0.0 directly from GitHub. Validation hangs due to GUI not finding progress,xml

This is because the ~/DASH-IF-Conformance/Conformance-Frontend/temp directory is not created when first run.

**Comment by dsilhavy** [comment]
We will replace the existing UI with a new one in 2.1.0. In the new UI we use the REST interface making the progress.xml obsolete.

**Comment by dsilhavy** [comment]
Update: Version 2.2.0 removes the old UI, we keep this issue open until the release

**Comment by dsilhavy** [comment]
New UI released, closing
