### ISSUE TITLE
Some CAs in common use don't seem to be trusted

### ISSUE THREAD

**Issue by sdp198** [Dash-Industry-Forum/DASH-IF-Conformance#62]
In particular loading an MPD with an https url from Akamai seems to fail with the message 
`Error loading the MPD, please check the URL.`

The certificate in question is trusted by firefox and signed by "DigiCert ECC Secure Server CA".  Is this supported by the backend of the validator?

**Comment by eceozturk** [comment]
Https urls are supported on the server. 
Closing this issue now. If the problem persists, please reopen.
