### ISSUE TITLE
dhtmlXTree looks to be missing

### ISSUE THREAD

**Issue by andyburras** [Dash-Industry-Forum/DASH-IF-Conformance#628]
I have done a pull from the https://github.com/Dash-Industry-Forum/DASH-IF-Conformance repo, but now the analysis is immediately hanging.
It looks like the dhtmlXTree tree directory has been deleted:-

```
Loading failed for the <script> with source “http://localhost/DASH-IF-Conformance/Conformance-Frontend/tree/dhtmlxTree/codebase/dhtmlxtree.js”. index.html:154:1
Loading failed for the <script> with source “http://localhost/DASH-IF-Conformance/Conformance-Frontend/tree/dhtmlxTree/codebase/ext/dhtmlxtree_json.js”.
```

But this is required by angular.js :-

```
Error: dhtmlXTreeObject is not defined
setUpTreeView@http://localhost/DASH-IF-Conformance/Conformance-Frontend/app/controllers/stepperController.js:456:13
submit@http://localhost/DASH-IF-Conformance/Conformance-Frontend/app/controllers/stepperController.js:369:16
fn@http://localhost/DASH-IF-Conformance/Conformance-Frontend/scripts/angular.min.js line 223 > Function:4:906
b@http://localhost/DASH-IF-Conformance/Conformance-Frontend/scripts/angular.min.js:122:181
e@http://localhost/DASH-IF-Conformance/Conformance-Frontend/scripts/angular.min.js:265:196
$eval@http://localhost/DASH-IF-Conformance/Conformance-Frontend/scripts/angular.min.js:141:47
$apply@http://localhost/DASH-IF-Conformance/Conformance-Frontend/scripts/angular.min.js:141:280
compile/</<@http://localhost/DASH-IF-Conformance/Conformance-Frontend/scripts/angular.min.js:265:247
dispatch@http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:3:8436
add/r.handle@http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:3:5139
angular.min.js:114:212
```

**Comment by dsilhavy** [comment]
@andyburras With the upcoming version (already merged to development) we are deprecating the old UI. The new UI is currently located in `Conformance-Frontend-JCCP`. We will move the content of this folder to the standard folder `Conformance-Frontend` with one of the next PRs before doing the official release

**Comment by andyburras** [comment]
Ah OK. So are the instructions at https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/wiki/Installation--guide out of date now, do I need to be updating/installing from a different branch to be getting a stable JCCP release?

**Comment by andyburras** [comment]
I can't seem to get a working validator now? If I use the development branch then fails due to missing JavaScript libs.

I did a clean install of the "master" branch, and the segment validation always crashes with :-

BAILIFERR: <../src/HelperMethods.cpp> (000048) BAILIFERR: <../src/ValidateAtomList.cpp> (000060) BAILED

even on files that used to pass through the validator.

**Comment by andyburras** [comment]
Resolved.
