### ISSUE TITLE
Issues with CMAF Section A.2 colour_primaries, transfer_characteristics and matrix_coefficients check

### ISSUE THREAD

**Issue by nicholas-fr** [Dash-Industry-Forum/DASH-IF-Conformance#649]
Issues encountered when testing CTA WAVE test content.

The first part of the issue is that the matrix_coefficients are not found resulting in a FAIL, but the overall status is PASS (should be FAIL if any of the 3 checks fail).

The second part of the issue is that in the content tested, valid matrix_coefficients are actually present:
![image](https://user-images.githubusercontent.com/9865551/225678309-12c4d86a-2b15-4d32-8ca3-a3cd99c0eeb6.png)

`docker exec -w /var/www/html/Utils/ <docker_ID> php Process_cli.php --cmaf --ctawave --segments http://dash-large-files.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t1/2022-10-17/stream.mpd`
```
{
"spec": "CMAF",
"section": "Section A.2",
"test": "For a CMAF Track to comply with one of the media profiles in Table A.1, it SHALL conform to the colour_primaries, transfer_characteristics and matrix_coefficients values from the options listed in the table",
"messages": [
    "Valid color primaries found",
    "Valid transfer characteristics found",
    "FAIL"
],
"state": "PASS"
}
```

**Comment by rbouqueau** [comment]
As far as I remember, the ```colr``` box parsing in the ISOSegmentValidator has been incomplete. Color Management support has greatly improved within the last couple of years, and so should the validator.
