### ISSUE TITLE
"Section 7.2.1: max tolerance of segment duration 0/-1 50%" maybe false positive?

### ISSUE THREAD

**Issue by Murmur** [Dash-Industry-Forum/DASH-IF-Conformance#656]
https://staging.conformance.dashif.org/

All segments should have an identical duration+number of fragments(moof/mdat pairs). All segments are fine except this one `Segment 11` line is flagged as an error. Do multiple moof/mdat pairs introduce side effects?

Each segment file is 3.84s with two 1.92s IFrame delimited fragments on each m4s file(moof/mdat pair).

**Section 7.2.1: The maximum tolerance of segment duration shall be +/-50% of the signaled segment duration.**
```
✓ Segment 0 with duration 1.88 is within bounds of signaled 3.84
✓ Segment 1 with duration 1.88 is within bounds of signaled 3.84
..
✓ Segment 10 with duration 1.88 is within bounds of signaled 3.84
✗ Segment 11 with duration 1.88 violates bounds of signaled 3.84
```

Test content, capped to 24s but real duration is 384s but it takes too much time to run on a conformance tool.
https://refapp.hbbtv.org/videos/00_llama_h264_v8/manifest_1080p_24s.mpd
https://refapp.hbbtv.org/videos/00_llama_h264_v8/manifest_1080p.mpd

**Comment by dsilhavy** [comment]
Addressed in #660 we had to add extend the logic of the testcases to support for multiple moof/mdat boxes. Can you please confirm that this is fixed on https://staging.conformance.dashif.org/

**Comment by Murmur** [comment]
Validator(staging) `Section 7.2.1: The maximum tolerance of segment duration shall be +/-50% of the signaled segment duration` rule works now with multiple moof/mdat pairs.

https://refapp.hbbtv.org/videos/00_llama_h264_v8/manifest_1080p_24s.mpd

**Comment by dsilhavy** [comment]
Thanks for testing @Murmur
