### ISSUE TITLE
"Section 7.2.1: The difference between MPD start time and presentation time shall not exceed +/-50%", wrong segdur formula?

### ISSUE THREAD

**Issue by Murmur** [Dash-Industry-Forum/DASH-IF-Conformance#657]
https://staging.conformance.dashif.org/

All segments should have an identical duration+two fragments(moof/mdat pairs). MPD static starttime is `0S` but I do not understand a reasoning for this error message.

`Video segment: dur=49152, timescale=12800, segdur=3.84s`
`Audio segment: dur=184320, timescale=48000, segdur=3.84s`

Message has `segment 0..n` sequence number but I think it refers to fragments, each segment is 3.84s with two 1.92s fragments on each m4s file(moof/mdat pair). Message is a bit misleading?

**Section 7.2.1: The difference between MPD start time and presentation time shall not exceed +/-50% of value of @duration divided by the value of the @timescale attribute**
```
✓ Correct for segment 0 with duration 0
✓ Correct for segment 1 with duration 1.92
✗ Incorrect for segment 2 with duration 3.84
✗ Incorrect for segment 3 with duration 5.76
...
✗ Incorrect for segment 11 with duration 21.12
✓ Correct for segment 0 with duration 0
✓ Correct for segment 1 with duration 1.92
✗ Incorrect for segment 2 with duration 3.84
✗ Incorrect for segment 3 with duration 5.76
...
✗ Incorrect for segment 11 with duration 21.12
✓ Correct for segment 0 with duration 0
✓ Correct for segment 1 with duration 1.92
✗ Incorrect for segment 2 with duration 3.84
✗ Incorrect for segment 3 with duration 5.76
...
```

Test content, capped to 24s but real duration is 384s but it takes too much time to run on a conformance tool.
https://refapp.hbbtv.org/videos/00_llama_h264_v8/manifest_1080p_24s.mpd
https://refapp.hbbtv.org/videos/00_llama_h264_v8/manifest_1080p.mpd

**Comment by dsilhavy** [comment]
Addressed in #660 we had to add extend the logic of the testcases to support for multiple moof/mdat boxes. Can you please confirm that this is fixed on https://staging.conformance.dashif.org/

**Comment by Murmur** [comment]
Validator(staging) `Section 7.2.1: The difference between MPD start time and presentation time shall not exceed +/-50% of value of @duration divided by the value of the https://github.com/timescale attribute` rule works now with multiple fragments(moof/mdat pair).
https://refapp.hbbtv.org/videos/00_llama_h264_v8/manifest_1080p_24s.mpd

**Comment by dsilhavy** [comment]
Thanks for testing @Murmur
