### ISSUE TITLE
Very high and sustained request volume from https://conformance.dashif.org/ to our Dash service

### ISSUE THREAD

**Issue by davediff** [Dash-Industry-Forum/DASH-IF-Conformance#666]
Seeing about 5-10 failed requests/second for the past 2 weeks coming from 54.72.87.160 (https://conformance.dashif.org/) for a single DASH segment. Is there any limiting that is in place to prevent the tool from making repeated failed requests? Would you be able to isolate the task that is making these repeated requests and cancel it? I can share the host name on our side that is seeing the failed requests offline.  Thanks!

**Comment by dsilhavy** [comment]
Do you know which MPD is causing this? We have some Github actions in place for regression testing but I dont think they cause this kind of traffic. Apart from that, we are not preventing any requests as the tool is open to users who can simply paste an MPD to be validated.

**Comment by dsilhavy** [comment]
Closing this for now as no more comments were made. Please comment if this is still an issue
