### ISSUE TITLE
Conformance tool 

### ISSUE THREAD

**Issue by scunning1987** [Dash-Industry-Forum/DASH-IF-Conformance#696]
https://conformance.dashif.org/

This URL returns :

_Not Found
The requested URL was not found on this server.

Apache/2.4.41 (Ubuntu) Server at localhost Port 8000_

**Comment by rbouqueau** [comment]
Weirdly https://staging.conformance.dashif.org/ is still up and running (in case it can help).

**Comment by rbouqueau** [comment]
Thanks for reporting. Up again! Please re-open if needed.
