### ISSUE TITLE
Many HTTP requests come from the Conformance server with IP 54.72.87.160

### ISSUE THREAD

**Issue by stepri** [Dash-Industry-Forum/DASH-IF-Conformance#702]
We've tried to debug a DASH manifest with this Conformance tool and since then we're getting hammered with requests coming from IP 54.72.87.160. This is happening since 19th April and we're receiving 227 million requests (!) per week (around 363 per second). We are currently blocking these requests, but it would be nice to see this stops

**Comment by Phencys** [comment]
Hello @stepri.

Our sincere apologies for this oversight. Traffic should have stopped by now. Can you please confirm so we can close this issue?

**Comment by stepri** [comment]
Yes, the traffic has stopped. Thank you!
