### ISSUE TITLE
Conformance Issue in TrickMode Representation: Sidx  referes to a moof which has no presentable samples (after applying edits). 

### ISSUE THREAD

**Issue by diegosuarez86** [Dash-Industry-Forum/DASH-IF-Conformance#73]
Dear All,

The following content presents an issue in TrickMode Representation: 

~9a/qualcomm/1/MultiRate.mpd

The log is:
### Sidx 1 reference 1 referes to a moof which has no presentable samples (after applying edits)

.
.
.
### Sidx 1 reference 296 referes to a moof which has no presentable samples (after applying edits)

I appreciate your help,

Regards,

Diego Suarez

**Comment by eceozturk** [comment]
This does not seem to be an issue anymore. Closing now. Please reopen if the issue persists.
