### ISSUE TITLE
Synchronous XMLHttpRequest deprecated 

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/DASH-IF-Conformance#77]
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

**Comment by waqarz** [comment]
This is a warning generated in console, not sure if this is still the case.

**Comment by dsilhavy** [comment]
Closing
