### ISSUE TITLE
DASH Validator: the chosen MPD is submitted without submit button being clicked

### ISSUE THREAD

**Issue by juzzlin** [Dash-Industry-Forum/DASH-IF-Conformance#81]
How to reproduce:

1) Click browse
2) Select your MPD
3) Observe that processing is immediately started without doing anything

It would be expected that after selecting the MPD user can check/uncheck "MPD conformance only" and then click "SUBMIT" to submit.

**Comment by eceozturk** [comment]
This issue is addressed in https://github.com/Dash-Industry-Forum/Conformance-Frontend/pull/54
