### ISSUE TITLE
DASH Validator: double-clicking is confusing

### ISSUE THREAD

**Issue by juzzlin** [Dash-Industry-Forum/DASH-IF-Conformance#82]
The error log link in the results of MPD validation requires double-clicking to get it opened. This is confusing since a single click should be used in web pages. It doesn't even look like anything that could be opened.

**Comment by eceozturk** [comment]
Double click is replaced with single click. The related feature is added via commit id 31f8f046859e0d3a062788d87234f8af14ac9e01 in https://github.com/Dash-Industry-Forum/Conformance-Frontend 

Closing this now.
