### ISSUE TITLE
Support Segment timeline for type dynamic

### ISSUE THREAD

**Issue by dsparacio** [Dash-Industry-Forum/DASH-IF-Conformance#83]
Conformance test completed
Segment timeline for type dynamic is not supported, only MPD will be tested.

Even though it says it will only test MPD I get errors.   But when I check MPD conformance only the MPD passes

**Comment by eceozturk** [comment]
SegmentTimeline with dynamic type MPDs is supported via PR #440. 
Closing this issue now. Please reopen if there is a related issue.
