### ISSUE TITLE
Does not accept ttml Mime type

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/DASH-IF-Conformance#84]
Broken rule:
			
			<assert test="if (@mimeType and not((@mimeType = 'video/mp4') or (@mimeType = 'audio/mp4') or (@mimeType = 'application/mp4'))) then false() else true()"> DASH-IF IOP (v3.3) Section 3.2.13: For Adaptation Sets the mimeType shall be one of the four following type: "video/mp4", "audio/mp4", or "application/mp4"</assert >

Should be:
			
			<assert test="if (@mimeType and not((@mimeType = 'video/mp4') or (@mimeType = 'audio/mp4') or (@mimeType = 'application/mp4') or (@mimeType = 'application/ttml+xml'))) then false() else true()"> DASH-IF IOP (v3.3) Section 3.2.13: For Adaptation Sets the mimeType shall be one of the four following type: "video/mp4", "audio/mp4", "application/mp4", or application/ttml+xml</assert >

**Comment by eceozturk** [comment]
This issue is addressed in old repository https://github.com/Dash-Industry-Forum/Conformance-Software and hence in the new one as well https://github.com/Dash-Industry-Forum/DASH-IF-Conformance
