### ISSUE TITLE
Dont run segment conformance for TTML files

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/DASH-IF-Conformance#85]
e.g. http://xyz/dash264/TestCases/4b/qualcomm/1/ED_OnDemand_5SecSeg_Subtitles.mpd

**Comment by eceozturk** [comment]
This issue is addressed in old repository https://github.com/Dash-Industry-Forum/Conformance-Software and hence also in the new one https://github.com/Dash-Industry-Forum/DASH-IF-Conformance
