### ISSUE TITLE
MPD validation fail: 29.97 fps isn't supported with following format: "30000/1001" which is defined by ISO/IEC 23009-1:2014(E)

### ISSUE THREAD

**Issue by mikilaor** [Dash-Industry-Forum/DASH-IF-Conformance#91]
The manifest I have, contains the following 29.97 fps  which is represented like this:
frameRate="30000/1001"

Manifest:
-----------
Representation id="video.1.L1" bandwidth="1499463" codecs="avc1.4d401f" width="640" height="360" frameRate="30000/1001" sar="1:1"

MPD validation fails:
------------------------
Line:Col[53:39]:cvc-datatype-valid.1.2.1: '30000/1001' is not a valid value for 'double'.
Line:Col[53:39]:cvc-attribute.3: The value '30000/1001' of attribute 'maxPlayoutRate' on element 'Representation' is not valid with respect to its type, 'double'.
Unexpected error: For input string: "30000/1001"
MPD validation not successful - DASH is not valid!

Spec:
-------
@frameRate
O
specifies the output frame rate (or in the case of interlaced, half the output field rate) of the video media type in the Representation. If the frame or field rate is varying, the value is the average frame or half the average field rate field rate over the entire duration of the Representation.
The value is coded as a string, either containing two integers separated by a "/", ("F/D"), or a single integer "F". The frame
ISO/IEC 23009-1:2014(E)
© ISO/IEC 2014 – All rights reserved 41
Use Description
Element or Attribute Name
rate is the division F/D, or F, respectively, per second (i.e. the default value of D is “1”).

**Comment by eceozturk** [comment]
The "framerate" attribute is of FrameRateType and it can process the values provided in the second image. This information is directly from the DASH-IF specification (23009-1)

On the other hand, the error message provided in your log points to "maxPlayoutRate" attribute which is specified to be of type double in the specification. See the first image. 

First image:
![image](https://user-images.githubusercontent.com/35132231/49227362-33653380-f3e9-11e8-8852-ea604f738dde.png)

Second image:
![image](https://user-images.githubusercontent.com/35132231/49227561-a53d7d00-f3e9-11e8-94d1-2ebdb8bdac84.png)

So, the MPD validation error is valid. Closing this issue now.
