### ISSUE TITLE
cvc-complex-type.3.2.2: Attribute 'selectionPriority' is not allowed to appear in element 'AdaptationSet'.

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/DASH-IF-Conformance#92]
I believe DASH amd4 added a `selectionPriority` attribute. I do not have the spec in front of me, so perhaps I am mistaken somehow but I seem to remember it being there, so this validation error for `AdaptationSet@selectionPriority` seems wrong to me.

**Comment by jnorthrup** [comment]
cross linking to https://github.com/google/shaka-player/issues/1877

**Comment by niteeshbhat** [comment]
The attribute selectionPriority has been added to DASH schema sometime back (https://github.com/Dash-Industry-Forum/DASH/blob/master/mpdvalidator/schemas/DASH-MPD.xsd).

Currently this error doesn't occur during conformance testing. (I just tested an MPD by adding this attribute).

If there is any MPD with selectionPriority and this error is observed in the current version of the software, please share the MPD or else the issue can be closed.

**Comment by sandersaares** [comment]
I confirm that I am no longer able to reproduce this error.

**Comment by jnorthrup** [comment]
https://trac.ffmpeg.org/ticket/7845  filed
