### ISSUE TITLE
Wrong file upload issue

### ISSUE THREAD

**Issue by niteeshbhat** [Dash-Industry-Forum/DASH-IF-Conformance#94]
Instead of a proper MPD, a wrong file like jpeg is uploaded, the software crashes at a particular point (xml loading). 
Identification of proper mpd may be required.

**Comment by eceozturk** [comment]
This issue is related to #361

**Comment by niteeshbhat** [comment]
This is fixed in MPDProcessing.php of DASH sub module.
The uploaded file passes only if the file has valid MPD DOM.
Tested with different file formats like jpg, png, c,php,pem etc. The alert "Error loading MPD, please check the URL" is raised.
Hence this issue can be closed.
