### ISSUE TITLE
Processing forever

### ISSUE THREAD

**Issue by christolb29** [Dash-Industry-Forum/DASH-IF-Conformance#96]
Hello,

I am using a manifest from the samples proposed in the dashif player (which works): http://dash.edgesuite.net/dash264/TestCases/1a/netflix/exMPD_BIP_TC1.mpd

The validator keeps processing forever and I get this message in the console : 
_conformancetest.php:387 GET http://54.72.87.160/conformance/current/webfe/temp/id9241753438/progress.xml?1506583688204 404 (Not Found)progressupdate @ conformancetest.php:387(anonymous function) @ conformancetest.php:453_

Thanks

**Comment by eceozturk** [comment]
This issue is now tracked at #442. Closing this now
