### ISSUE TITLE
The processing instruction target matching "[xX][mM][lL]" is not allowed.

### ISSUE THREAD

**Issue by niteeshbhat** [Dash-Industry-Forum/DASH-IF-Conformance#97]
SAXException error -The processing instruction target matching "[xX][mM][lL]" is not allowed.
observed for mpd with query string , 

https://wowza03.cdr.nl/EncAudio/mp4:KAX8252-0001.m4a/manifest.mpd?TOKENCHUNK=VE9LRU49MjU2MjY5MTY4MzI3OTk2MTY1NCZET01BSU49d3d3LmRldi1tdXppZWt3ZWIubmw=

**Comment by eceozturk** [comment]
Fixed in https://github.com/Dash-Industry-Forum/DASH/pull/35
